udo-munk/z80pack

z80sim/srcsim/disas.c
I've fixed the format of RST for the 8080 disassembler so that, e.g., it will output RST 1 instead of RST 8.
Attached, is a test that I developped to reassure me of the correctness of the 8080 disassembler.  Simply untar it in the simulator subdirectory, cd testd80 and type make.
8080.asm, contains all 8080 instructions, and has been generated from an independent source.
8080.bin is the corresponding assembled binary.
The test consist of disassembling 8080.bin with disas() and comparing the result with 8080.asm (transformed by a script so that the syntax matches).
[testd80.tar.gz](https://github.com/udo-munk/z80pack/files/1754661/testd80.tar.gz)
=> Make RST format in 8080 disassembler compatible with Intel and DRI asm

z80sim/srcsim/disas.c, z80sim/srcsim/simctl.c
The disassembler doesn't wraparound from high addresses to low addresses when a instruction is near the end of the memory. It picks garbage bytes just after the memory.
E.g. assemble LD HL,1234h from FFFF:
```
>>> m ffff
ffff = 65 : 21
0000 = cb : 34
0001 = fb : 12
0002 = 66 : q
```
and disassemble it:
```
>>> lffff
ffff - LD	HL,00DF
...
```
I've fixed this problem by adding one more parameter to disass(), the memory base. When it is not null, base will be considered as the base of the simulated memory and wraparounds will be handled.
Of course, addresse wraparound is also handled when computing relative jumps addresses.
There are probably more elegant solution bu this one requires less changes.
=> Fix address wraparound problem in disas

frontpanel/lp_main.cpp, z80sim/srcsim/sim1.c, z80sim/srcsim/sim1a.c
This Pull-Request contains proposed fixes for two issues:
- Redundant frontpanel updates being made in `sim1.c` and `sim1a.c` #8 
- No mutex initialisation for data_sample_lock in `lp_main.cpp` #7
=> fixed: mutex initialisation and redundant frontpanel updates

imsaisim/srcsim/iosim.c, imsaisim/srcsim/simctl.c, z80sim/srcsim/sim0.c
The IMSAI documentation states that the External Clear toggle is wired (via a diode) to the Reset toggle line so that a processor reset also occurs when when an External Clear is performed
Based on the previous change it looked logical to add a `reset_io()` function to the `iosim.c` module
A lot of simulated hardware initialisation is occurring in the `simctl.c` module `mon()` function, meanwhile the `iosim.c` module `init_io()` function has remained empty. It seems like a good separation-of-concerns to move this simulated hardware initialisation to `init_io()`
1. there are duplicate calls to `load_core()`. One is made in the `sim0.c` module `main()` function, the second is made in the `simctl.c` module `load()` function.
2. With the above change to move simulated hardware initialisation …
=> Refactor code out of simctl.c to improve separation of concerns for hardware IO simulation

imsaisim/srcsim/config.c, imsaisim/srcsim/sim.h, iodevices/imsai-fif.c, z80sim/srcsim/sim0.c, z80sim/srcsim/simglb.c
Note: The use of `MAX_LFN` in `sim0.c` and `simglb.c `will require this `#define` to be added to `sim.h` for all machines.
=> Put a few values into #defines in sim.h to help with platform portability and machine configuration

imsaisim/conf_3d/system.conf, imsaisim/srcsim/config.c, iodevices/imsai-sio2.c
This addresses the issue identified with `poll()` #15 leading to high CPU utilisation.
=> Simulated baudrate on serial I/O

imsaisim/srcsim/iosim.c, imsaisim/srcsim/memory.h, imsaisim/srcsim/simctl.c
These updates are a result of reading the manual for the IMSAI 8080 CP-A front panel and looking at videos of a real IMSAI 8080 CP-A front panel in operation. How I wish I had a real machine to compare with.
=> Updates to behaviour of Data Bus LEDs to more closely simulate the IMSAI 8080 CP-A front panel

imsaisim/srcsim/memory.h, iodevices/imsai-vio.c
For performance reasons every memwrt() should **not** have to check for the VIO mode control byte.
It is enough for the VIO refresh() loop to do this each time, and using a double-buffer for the mode control byte pays back for cost of the dma_read(0xf7ff).
=> Update: Issue #35 - let VIO handle mode in refresh loop not in memwrt()

imsaisim/conf_2d/system.conf, imsaisim/conf_3d/system.conf, imsaisim/srcsim/iosim.c, imsaisim/srcsim/memory.c, imsaisim/srcsim/memory.h
- Fixes a bug in the banked ROM code when `ram_size` < 56K
- Improves readability of memory events with the use of some macros
- Improves on solution for #36 by also releasing the RAM as well as the ROM (also cares about `ram_size`)
- Updates the `system.conf` files for the 64K maximum RAM size now supported
=> Bug fix in banked ROM, improve readability for memory events, enhance VIO release of memory

imsaisim/srcsim/Makefile.osx, imsaisim/srcsim/log.h, imsaisim/srcsim/memory.c
Described in #45.
Look at the example use in `memory.c` included in this PR.
Compile and run:
```
CPU speed is 2 MHz, CPU executes undocumented instructions
RAM size is 64 KB
I (13369) memory: MPU-B Banked ROM/RAM enabled
Loader statistics for file mpu-a-rom.hex:
START : d800H
```
Un-comment the line `memory.c:23`, compile and run:
```
CPU speed is 2 MHz, CPU executes undocumented instructions
RAM size is 64 KB
I (15604) memory: MPU-B Banked ROM/RAM enabled
D (15614) memory: MPU-B Banked ROM/RAM group select 00
Loader statistics for file mpu-a-rom.hex:
START : d800H
```
You could also set the value `#define LOG_LOCAL_LEVEL LOG_WARN` on `memory.c:23` and then you wouldn't see any message logged about the banked memory.
=> Added a light-weight logging library, self contained in log.h

imsaisim/srcsim/Makefile.osx, imsaisim/srcsim/iosim.c, imsaisim/srcsim/sim.h, iodevices/diskmanager.c, iodevices/imsai-fif.c
Finally ready to go.
Include/exclude with `#define HAS_DISKMANAGER` in `sim.h`
Notes on use are in the comments in `iodevices/diskmanager.c`
The module `iodevices/diskmanager.c` also includes the code that uses the diskmanager functions for insert/eject of the virtual disks `X:DSK:` and provides the library `LIB:` for the web UI. These are currently disabled behind `#ifdef HAS_NETSERVER`. Don't enable this now, it is included here as a preview of the webserver interface.
=> Disk manager module and integration 

imsaisim/srcsim/Makefile.osx, imsaisim/srcsim/iosim.c, imsaisim/srcsim/sim.h, imsaisim/srcsim/simctl.c, iodevices/diskmanager.c, iodevices/imsai-sio2.c, iodevices/imsai-vio.c, webfrontend/civetweb.h, webfrontend/netsrv.c, webfrontend/netsrv.h
The next step in the code release for #38 
This compiles when `HAS_NETSERVER` is not defined. That is the point of this PR.
If you try to build it with `HAS_NETSERVER` it will **compile** but not **link** because the **civetweb** library has not been included. There will be a seperate PR with source, makefile and notes for building `libcivetweb.a`
It will be located in the `webfrontend` directory along with the `netsrv` module.
The other piece that is not included is the frontend code (HTML/CSS/JS). This will also be in a seperate PR.
=> Integrate webfrontend network services into the imsaisim and related iodevices (TTY: VIO: LPT:)

altairsim/srcsim/GNUmakefile, imsaisim/srcsim/GNUmakefile
Fixes build issue on Linux (Ubuntu 16.04) for me. 
There are some conflict with the ordering of libraries for the linker.
What the `GNUmakefile` produces now it almost the same as the existing build system and works for me.
=> Updates to GNUmakefile for altairsim & imsaisim 

webfrontend/README.md
The urls in README hadn't been entered for the links in the README.MD for webfrontend.  These are now correct.
=> Correct urls in Webfrontend README.md

imsaisim/boot, imsaisim/bootvio, imsaisim/conf_2d/system.conf, imsaisim/conf_3d/system.conf, imsaisim/cpm22, imsaisim/cpm3, imsaisim/imdos202, imsaisim/imdos205r0, imsaisim/imsai-cpm13, imsaisim/srcsim/config.c, imsaisim/srcsim/config.h, imsaisim/srcsim/iosim.c, imsaisim/srcsim/memory.c, imsaisim/srcsim/memory.h, imsaisim/srcsim/simctl.c, imsaisim/ucsd, imsaisim/um-cpm13, z80core/sim0.c, z80core/simfun.c, z80core/simglb.c, z80core/simglb.h
NOTES:
- the **altiarsim** will be temporarily broken, because **sim0.c** no longer calls **init_rom()**
- other machines wont notice because their **init_rom()** is empty
- the `-x filename` command still works, but does not tag the loaded memory space as ROM (it never has)
- `load_file()`, `load_mos()`, `load_hex()` and `checksum()` did move out of `sim0.c` and into `simfun.c`
-  they did not look like they should belong in `sim0.c`
=> implement new memory config strategy using system.conf ram/rom/boot directives

altairsim/boot, altairsim/conf/system.conf, altairsim/cpm22, altairsim/srcsim/config.c, altairsim/srcsim/config.h, altairsim/srcsim/memory.c, altairsim/srcsim/memory.h, altairsim/srcsim/sim.h, altairsim/srcsim/simctl.c
I have updated the **altiarsim** to use the same changes to the  `system.conf` ram/rom configuration strategy.
Note:
- the `tarbell_rom_enabled` directive has been removed from `system.conf` and replaced with the `-R` command line flag
- I used educated guesses for the correct ROM files (*.hex) for each `[MEMORY n]` section in `system.conf`
- this is not tested very much as I am unfamiliar with the **altairsim** and don't know what to expect
- only the start scripts `boot` and `cpm22` have been updated so far, the remainder need to be updated
=> update altairsim to new ram/rom config strategy

cromemcosim/dzmation.asm
I was getting frustrated that I could not punch a tape from dazzlemation even after setting the EQUates for DATAPORT and STATPORT for the IMSAI SIO
It took me a long time to realise that the OUT instructions still had port 01H hardcoded and were not using the EQUates
=> fix - use EQUates for OUT instructions

z80sim/srcsim/simctl.c
this should fix an error i encountered in z80sim which causes problems when loading hex files
```
Release 1.38-dev, Copyright (C) 1987-2021 by Udo Munk
CPU speed is unlimited, CPU executes undocumented instructions
>>> r float.hex
W (0) func: tried to load hex record outside expected address range. Address: 0000-0020
>>>
```
commit 93c56c1a8e82baceea041ac416b4165f138c49c1 changed the function prototype for `load_file()` but the externs in z80sim never got modified.
=> fix error causing load hex file error

z80core/sim0.c, z80core/sim2.c, z80core/sim3.c, z80core/sim4.c, z80core/sim5.c, z80core/simglb.c, z80core/simglb.h
The 7th bit of R must not be modified between LD R,A and LD A,R, so keep a copy of it in new R_ CPU state variable.
Save/load R_ with with save_core()/load_core().
Old core.z80 files are incompatible.
These functions should probably be moved to memory.c and reimplemented to make them work with banked memory.
Increment R for each opcode fetch.
Not sure of what happens with 0x[df]d 0xcb. MAME and the FUSE emulator also doesn't increment R there.
Unrolled block instructions need to increment R by 2 in each loop.
=> z80core: more correct handling of refresh register

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, z80core/sim1.c, z80core/sim1a.c, z80core/sim4.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
1. Generalized looping support for all block instructions by changing WANT_FASTM to WANT_FASTB and adding missing single step versions. This is, for example, needed for the CPU test program from github.com/raxoft/z80test, which has a self-modifying LDIR/LDDR test (just realized that already hat single step versions...).
2. Changed io_out declarations from "BYTE" to "void", which it really is.
3. Changed standard flags settings for the I/O block instructions according to "The Undocumented Z80 Documented".
4. B is decremented before port output in OUT block instructions according to the Aug 2016 edition of the "Z80 CPU User Manual".
5. Overstepped my authority ;-) and changed VERSION in sim.h.fast, which was forgotten by the project creator.
=> z80core: add single step version for all block instructions, flags for i/o

doc/README-asm.txt, mosteksim/srcsim/simctl.c, z80asm/COPYING, z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80anum-orig.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c, z80sim/8080opsall.asm, z80sim/Makefile, z80sim/srcsim/disas.c, z80sim/srcsim/iosim.c, z80sim/srcsim/simctl.c, z80sim/z80opsall.asm
1. Added remaining undocumented Z80 instructions to dis-/assembler.
2. Cleaned up and deduplicate code in z80arfun.c.
3. Fixed (IMHO) chk_v1 & chk_v2 functions and renamed them to chk_byte & chk_sbyte to make they purpose more clear
4. Bonus feature: added support for 8080 mode in the assembler since the simulator and disassembler already support it.
5. Added 8080opsall.asm to test dis-/assembler.
6. Increased version number of the assembler because of the many changes.
7. Added copyright notices and history to assembler.
8. Added copyright notice to disas.c.
Added second commit to fix some cosmetic stuff and typos.
To hide my own errors ;-) (checking thousands of lines of diffs before pushing makes my eyes bleed...),
I included cleanups for a file which I overlooked in my previous clean …
=> z80asm/z80sim: added remaining undoc'd instructions to dis-/assembler & 8080 asm

z80asm/Makefile, z80asm/z80anum.c, z80asm/z80apfun.c, z80asm/z80arfun.c
Added an `(unsigned)` cast to a strlen comparison and changed functions without parameters
from `()` to `(void)` in z80anum.c. This accounts for the object code differences to the old version
of z80anum.c.
=> z80asm: reformat z80anum.c and make z80asm compile with -Wextra without warnings

doc/CREDITS, doc/README-asm.txt, z80core/COPYING, z80core/sim0.c, z80core/sim2.c, z80core/sim3.c, z80core/sim4.c, z80core/sim5.c, z80core/sim6.c, z80core/sim7.c, z80core/simglb.c, z80core/simglb.h
1. Added rest of 0xed undocumented instructions, all mirrors of documented ones.
2. Added rest of 0x[df]d 0xcb undocumented instructions. The BIT instructions are just mirrored.
3. Added copyright to files with functional changes by me, and also to COPYING to indicate that I put my changes under the same terms.
4. Added myself to CREDITS, to save the project leader some work.
5. Removed one lonely TAB character.
This completes the implementation of the undocumented instructions. All op-code planes are now completely covered.
Please feel free to change the wording in CREDITS.
=> z80core: added remaining undocumented Z80 instructions

z80core/sim1.c, z80core/sim2.c, z80core/sim3.c, z80core/sim4.c, z80core/sim5.c
All described in "The Undocumented Z80 Documented"
1. R needs to be incremented before instructions are executed. (really only affects "LD A,R")
2. Taking any interrupt increments R
=> z80core: further improvements to refresh register accuracy

doc/CREDITS, z80core/sim4.c
This partially reverts commit ae6346b6901d ("z80core: add single step version for all block instructions, flags for i/o")
Stop fiddling with undocumented flags. These are influenced by too many circumstances (NMOS, CMOS, Mask version, interrupts, unlicensed clones, ...)
=> z80core: remove undocumented flags from I/O block instructions

z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. Seperate pseudo ops from opcodes to make it easier to add new ones
2. Add a few pseudo op aliases, and two simple new ones: DEFC DEFZ
3. Refactor the Z80 CB opcodes code
4. Improve Z80 IN and OUT syntax checks
5. Anglicize some variables and strings
6. Clean-up my clean-up of z80anum.c
7. Some small reformatting
=> z80asm: seperate pseudo ops from opcodes, other small stuff

z80asm/z80anum-orig.c, z80asm/z80anum.c
`check_sbyte()` should accept -128, since this is inside the two complement's range.
Also accept -256..255 for `check_byte()` as, for example, specified by Intel
in their 8080/8085 Assembly Language Programming Manual.
That is check_byte accepts all 256 values for both positive and negative values,
and check_sbyte accepts all 256 values for two's complement values.
Sorry for getting this wrong in my previous commit.
=> z80asm: fix check_sbyte to cover complete byte two complement's number range

z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80anum-orig.c, z80asm/z80anum.c, z80asm/z80aout.c, z80asm/z80apfun.c
String separator => string delimiter.
Lexical scanning really attracts goto's. Looks actually cleaner now.
Use new error message for invalid expression.
Bug fix: X'h' constants need to be upcased, since they are inside strings.
=> z80asm: clean up and bug fix in the new expression parser

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, mosteksim/srcsim/simctl.c, z80asm/z80a.h, z80asm/z80anum-orig.c, z80asm/z80anum.c, z80core/simfun.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast, z80sim/srcsim/simctl.c
isxdigit has been part of the C standard since 1989.
=> remove isxdigit macro and use correct type cast for ctype function arguments

z80asm/z80amain.c
Previously only the pseudo-ops .PHASE, DEFS, DEFB, DEFM, and DEFW
would call put_label() if a label was present. I relaxed this, in my changes to drive put_label()
with the opcode table, to every pseudo-op except DEFL and EQU, but unintentionally
allowed put_label() calls for IF & co. when gencode is 0.
=> z80asm: never define label when gencode is 0

cromemcosim/roms/z1mon-1.4.lis, imsaisim/roms/basic4k.lis, z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80aopc.c, z80asm/z80apfun.c
Also update listings, because the END argument causes a previously unused label to be referenced.
Change DEFS to evaluate second parameter only during pass 2.
=> z80asm: don't hardcode END pseudo-op, use op_type and check optional argument

doc/README-asm.txt, z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c
1. Fixed non-sequential code detection. Flag wasn't initialized.
Just reversed it...
2. There was another problem with binary output files when there
is code generated before the first ORG, which sets the load address.
You'll get an error during assembly now, when this happens.
The object file produced should still be valid, it just won't
contain any code from before the first ORG address.
3. ad_mode needs to be reset at the start of pass 2 since pseudo-ops
set it regardless of the current pass. And because lst_line() isn't
called during pass 1, ad_mode won't be reset to AD_STD.
4. moved UNUSED macro to z80a.h
5. forgot to mention: moved lst_line() after obj_writeb(), so that error
messages from obj_writeb() will be shown on the correct source line.
6. make file name extensions …
=> z80asm: fix non-seq, detect code before ORG, ad_mode needs reset, UNUSED moved

doc/README-asm.txt, z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c
1. Forgot to convert op_ds() to use copy_arg()
2. It is now an error to leave out .DEPHASE
3. Put ORG, .PHASE and .DEPHASE in one function. They belong together.
4. Always set ad_mode at beginning when possible (nearly all pseudo ops already did this)
=> z80asm: use copy_arg() in DEFS, check for missing .DEPHASE, some re-org

cpmsim/srcsim/iosim.c, cpmsim/srcsim/memory.h, iodevices/cromemco-88ccc.c, mosteksim/srcsim/memory.h, mosteksim/srcsim/simctl.c, z80asm/z80amain.c, z80core/sim0.c, z80core/simfun.c, z80sim/srcsim/disas.c, z80sim/srcsim/memory.h, z80sim/srcsim/simctl.c
1. Removed mem_base() and wrk_addr everywhere. simctl.c now uses getmem() and putmem() to access memory. There is a new static variable wrk_addr of type WORD, which should avoid any wraparound problems. It's initialized to PC in mon(). I also set wrk_addr to PC in do_step(), so that one can simply type "l" to see the next instructions that will be executed.
2. Synced mosteksim/srcsim/simctl.c with z80sim/srcsim/simctl.c.
3. The disassembler just looked to "switch"ey...
4. Changed hex loader to set PC to start address in EOF record
=> z80sim: removed mem_base() and wrk_addr, reworked disassembler

altairsim/srcsim/GNUmakefile, altairsim/srcsim/Makefile.bsd, altairsim/srcsim/Makefile.osx, cpmsim/srcsim/GNUmakefile, cpmsim/srcsim/Makefile.bsd, cpmsim/srcsim/Makefile.osx, cromemcosim/srcsim/GNUmakefile, cromemcosim/srcsim/Makefile.bsd, cromemcosim/srcsim/Makefile.osx, imsaisim/srcsim/GNUmakefile, imsaisim/srcsim/Makefile.bsd, imsaisim/srcsim/Makefile.osx, iodevices/apu/am9511.c, iodevices/cromemco-88ccc.c, iodevices/cromemco-wdi.c, iodevices/diskmanager.c, webfrontend/netsrv.c, z80sim/srcsim/GNUmakefile, z80sim/srcsim/Makefile.bsd, z80sim/srcsim/Makefile.osx
1. Removed -Wno-self-assign from GNUmakefile and Makefile.*
2. Resolve remaining compiler warnings:
iodevice/apu/am9511.c: Added UNUSED macro, since it doesn't use sim.h
iodevices/cromemco-88ccc.c: Explicitly include <string.h> since it uses memset (netsrv.h already includes it, but...). Moved "#ifdef HAS_CYCLOPS" before including log.h.
iodevices/cromemco-wdi.c: Changed strncpy to memcpy. Explicitly cast st_size to long long.
iodevices/diskmanager.c: Moved "#ifdef HAS_DISKMANAGER" before including log.h.
webfrontend/netsrv.c: Moved "#ifdef HAS_NETSERVER" before including log.h. Explicitly cast st_size to long long. Fixed strncpy to always '\0' terminate string.
=> remove -Wno-self-assign, resolve warnings

cpmsim/srcsim/iosim.c, cpmsim/srcsim/memory.c, cromemcosim/srcsim/memory.c, frontpanel/Makefile.bsd, frontpanel/Makefile.cygwin, frontpanel/Makefile.linux, frontpanel/Makefile.osx, iodevices/apu/am9511.c, iodevices/cromemco-hal.c, iodevices/cromemco-hal.h, iodevices/cromemco-tu-art.c, iodevices/cromemco-wdi.c, iodevices/generic-at-modem.c, iodevices/generic-at-modem.h, iodevices/imsai-hal.c, iodevices/imsai-hal.h, iodevices/unix_network.c, webfrontend/netsrv.c, webfrontend/netsrv.h, z80asm/z80amain.c, z80asm/z80atab.c, z80core/log.h, z80core/sim6.c, z80core/sim7.c
... except one line in webfrontend/civetweb/src/md5.inl.
General: Added void to functions without parameters. Casts of malloc() result. Casts of int to enum (C++ doesn't do that automatically, since int and enums are separate types there).
cpmsim/srcsim/iosim.c: disks[] was initialized with negative tracks and sectors values, but these are defined as unsigned. telnet_negotiation() used unsigned char range values with a char array.
frontpanel/Makefile.*: Added -Wno-register to CFLAGS
iodevices/{cromemco-hal.c, imsai-hal.c}: They actually do include sim.h. Removed UNUSED macro.
iodevices/cromemco-tu-art.c: Doubly defined variable.
iodevices/unix_network.c: telnet_negotiation() used unsigned char range values with a char array.
webfrontend/netsrv.c: Enclosed a range of statements inside a …
=> clean up, everything now also compiles cleanly & runs using a C++ compiler

doc/README-asm.txt, z80asm/Makefile, z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. Fixed a bug I introduced in get_opcode() by using isspace(). This caused the '\n' to be skipped, and since there was no check for '\0'... spectactular crash on empty lines...
2. Fixed ELSE. I broke it...
3. Added range check for -e option.
4. Added myself to COPYR.
5. Intel-like macros.
6. Increased IFNEST for macros.
7. Changed A_* to explicit pseudo-ops.
8. Moved condnest to globals for macros (EXITM, ENDM).
9. Since condnest is now global, moved macro specific IF* to macro module.
10. Moved s_line to lst_line as static variable.
11. Word operators are no longer usable when defined as symbols, just like other opcodes when redefined as macros.
12. This allowed NUL to be implemented correctly. Hopefully...
13. Moved INCLUDE list processing to main line loop.
14. Let DEFS return an …
=> z80asm: bug fixes, Intel-like macros, misc stuff

doc/README-asm.txt, z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80aout.c, z80asm/z80apfun.c
1. The sorted macro list had the reference mark wrong.
2. Allow PAGE without operand as EJECT alias for MAC compatibility.
3. EJECT and PAGE without operand are printed on the current page.
3. Support "PAGE 0" nearly like MAC. Instead of producing no headers, add one header at the top of the list file.
4. Execute the first "PAGE" with operand in pass 1, to allow "PAGE 0" to work.
5. Add "-p" option to set page length between 6 - 144 or 0.
6. There is no more form feed at the start of the list file.
You now need to check that your line printer is at the start of a page...
Perhaps "-p0" is best for the list files included in the repository?
=> z80asm: fix sorted macro list, add "page 0" and "page" support

z80asm/z80aout.c
Don't panic :-), the first commit doesn't change the listing output. I'm done with listing changes.
I compared all the hex files in the repository with the ones generated with this changes.
They all match, except imsaisim/roms/basic4k.hex. The original hex file contains a few unnecessary
hex flushes and the beginning (all the ORGs for the RST vectors), this causes massive diffs.
I did a load and core save with z80sim -m0 -s and compared the core files. The memory content matches.
All the *.asm files on the xybasic disk now assemble and the hex files match the ones on the disk.
=> z80asm: don't do unnessesary hex flushes on ORG and DEFS

z80asm/z80amfun.c, z80asm/z80arfun.c
Remove some code from before I had the register values fully assigned.
Use the same coding style everywhere
Don't convert symbols inside strings to upper case for macro parameter substitution.
=> z80asm: remove unnecessary code & coding consistency, macro fix

z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
This is a rather large commit, since my playing around with Coherent 3.2 unearthed some problems with the code.
1. Expression evaluation needs to be done with 16-bit unsigned arithmetic, otherwise one gets problems like "(1 EQ 1) SHR 1" resulting in 0xffff and not 0x7fff.
2. Just bitten the bullet and introduced BYTE and WORD like in z80core and used them where applicable.
3. Listing line counting needs to be done with long's, since, for example, the full macro expansion listing of ex.mac has 157226 source lines.
4. Don't use sprintf, since Coherent's is not usable. It doesn't return the number of characters printed.
5. Do '%x' formatting by hand, since Coherent's is upper case.
6. Couldn't stop and have redone the register/flags number assignments so that "<< 3" shifting is no longer …
=> z80asm: use BYTE & WORD, don't use sprintf, do own %x, REG* again

cpmsim/srcsim/iosim.c, cpmsim/srctools/Makefile, cpmsim/srctools/cpmrecv.c, cpmsim/srctools/cpmsend.c, doc/README-cpm.txt
The names of the cpmsim tools send and receive are a bit too generic. Make them more specific to z80pack.
=> cpmsim: rename send & receive tools, names are to generic

doc/README-asm.txt, z80asm/z80anum.c
As long as one doesn't use macros there is no problem with these. Better than removing all the other operators that clash with macros.
=> z80asm: add % and ^ operator aliases and some advice

z80asm/Makefile, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80arfun.c
1. '$' in the first column is only treated as an option line if not followed by a valid symbol character (MAC uses '$*', '$+', and '$-' for options). This caused errors with z80dis.asm.
2. Some code clean-up...
=> z80asm: '$' labels fix, some clean-up

z80asm/z80atab.c
Symbol table looks nicer when symbols with equal values are sorted by name.
We now have only one sort routine (qsort) instead of 3 in the binary on Coherent.
Saves space :-) Sorry for your neatly written code.
=> z80asm: just use qsort() like the macro code, sort by name when equal values

z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. Moved line upcasing into the fgets block, since during macro expansion the lines are already upcased.
2. Fixed a memory leak in the macro code discovered by valgrind.
3. is_sym_char and is_first_sym_char were in the top 4 when running valgrind's callgrind. Removed is_sym_char and is_first_sym_char and made them into macros with a ctype-like array to check for symbol characters. Since I now had this array just used it for all character classifications.
4. Now strcmp and search_op were in the top 4 of the callgrind list. Built a single sorted list of struct opc * with all opcodes when switching the instruction set. Reduced instructions count for strcmp by half, and search_op by 60% when assembling ex.mac!
5. Just keep counters of the number of symbols and macros defined, and remove the …
=> z80asm: macro memory leak fix, optimizations, clean up

z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80atab.c
1. Move the rest of the opc code into z80aopc.c. It now contains the only code handling the opc and ope tables. Make the arrays and variables static like the macro code.
2. Convert symbol list to iterator style like the macro list. Now there is only one function to list the symbol table. main() is really short now.
3. z80atab.c now contains only symbol table code and is the only code that handles the internals of the symbol table. Make symbol table and variables static.
4. Clean up... should I even mentions this :-)
And it still compiles and runs on Coherent 3.2.
=> z80asm: code reorg, iterator style symbol table list, clean up

doc/README-asm.txt, z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. inc_line in struct inc should be unsigned long.
2. op_count should be WORD because of DEFS. All op_* functions return a WORD.
3. Revert most unsigned changes, I had overdone this. They will never reach INT_MAX on 16-bit OS's. Keep line counters as unsigned long, since they actually break 16-bit.
4. Revert LENFN check change. filename's are LENFN + 1 sized.
5. tmp is back for real. Used by the expression parser and the macro code.
6. Size line and tmp to MAXLINE+2 and the other buffers to MAXLINE+1 to actually allow a source line with 128 characters.
7. Change reference counter to flag, since it is only used as that.
=> z80asm: inc_line is long, op_count is WORD, revert some unsigned's, misc

iodevices/generic-at-modem.c, z80asm/z80anum.c
like cromemco-wdi.c
avoids a warning when compiling with -m32
The real fix would be to use "%zu" for size_t and "%zd" for ssize_t variables,
but this is a C99 feature and there was a commit removing use of C99 features.
=>  change printing of size_t var to explicit cast to long long and %lld

frontpanel/lp_gfx.cpp, frontpanel/lp_switch.cpp, frontpanel/lp_utils.cpp, frontpanel/lp_window.cpp, frontpanel/lpanel.cpp, frontpanel/lpanel.h
All this stuff was found with valgrind, what a great tool!
1. The XVisualInfo *vi in Lpanel::openWindow was never freed with XFree(). Make vi an instance variable of Lpanel and free it in Lpanel::closeWindow.
2. The namelist allocated by xpand() was not deallocated by its users.
3. lpObject::name was not deallocated in the destructor.
4. lpSwitch::object_ref_names was not deallocated in the destructor.
5. Parser::addArg was trying to minimize string allocations by reusing existing ones, but always allocated a new string and leaked the old one if it was reusable.
6. lpLight::start_clock was not initialized in the constructor.
7. The allocation of fname in Lpanel::readConfig was one character short.
=> frontpanel: fix memory leaks, uninitialized variable and string allocation

z80asm/z80a.h, z80asm/z80amfun.c, z80asm/z80aout.c
Clean up these most cryptic functions of the macro code. Add some comments.
Ensure that the buffers don't overflow during pass by value and dummy substitution.
=> z80asm: clean up mac_subst and mac_next_parm, add buffer overflow checks

frontpanel/lp_utils.cpp
This is only intended for ftime(3), an old V7 routine, which isn't even used by the frontpanel library.
When compiling on FreeBSD it produced a warning that it is deprecated.
=> frontpanel: remove #include <sys/timeb.h>

iodevices/generic-at-modem.c
cromemcosim and imsaisim didn't compile on FreeBSD, because struct sockaddr_in[6] weren't declared.
Fix this by including <netinet/in.h> and move <arpa/inet.h> after the <netinet/*> includes as specified in the FreeBSD inet_ntop(3) manpage.
=> build fix for FreeBSD

z80asm/z80amain.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80core/simdis.c
I always wondered why the assembler only allowed (IX+d) and not (IX-d), as d is a signed value. And of course M80 accepts (IX-d).
Fix this in the assembler, and also change the disassembler to print (IX-d) for negative offsets.
And a bit of clean up
=> allow '-' and '+' for index register offsets

z80asm/Makefile, z80asm/z80aglb.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80arfun.c, z80asm/z80atab.c, z80core/simdis.c, z80sim/z80opsall.asm
Allow (ix) and (iy) for index register usage wihout offset in the assembler.
Change the disassembler to the same.
Add all variations (IX), (IX+5), (IX-5) to z80opsall.asm to test the assembler and disassembler.
I really opened a can of worms here :-)
But see for example, https://bitsavers.org/components/zilog/z80/03-0029-01_Z80_CPU_Technical_Manual_1977.pdf
page 67 (73 in the pdf) for (IX) notation.
I was looking for any example of (IX-d) notation, but all examples in the manuals I checked always used positive offsets...
Added some small clean up
=> also allow (ix) notation for 0 offset

z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80aopc.c, z80asm/z80arfun.c
Convert op_ex() to use get_reg(). This function just looked out of place... and REGISP is now finally being used.
Convert two "if (get_reg() ==" to "switch(get_reg())". This didn't look right...
All asmerr()'s that don't depend on eval() return an opcode count of 0.
Always list a macro expansion line if an error occurred.
And I will never again say the assembler is done :-)
=> z80asm: clean up z80arfun.c

doc/README-asm.txt, z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c
The ops array doesn't need to be larger than MAXLINE. The longest opcode sequence created is a DB with one long string.
Remove include nesting array. INCLUDE is a recursive call of process_file. Just keep line and file info on the stack. Keep nesting level check to detect infinite recursive includes.
Don't call lst_header and lst_attl in INCLUDE. Just force eject page in code already present in process_line. The only user of lst_* functions is now the main module.
Add comment to confusing line in lst_line.
=> z80asm: limits part 2, add some comments

z80asm/z80a.h, z80asm/z80anum.c, z80asm/z80atab.c
I didn't know C, one needs to cast a signed value to an unsigned type of the same size, otherwise C first sign extends, i.e. a `char` cast to `unsigned` is sign extended, casting to `unsigned char` does the thing one wants.
I wondered if the hash() function was any good. It turns out it is really bad...
So I searched for a simple and fast better one.
The new function is a 16-bit version (so that it works as fast as possible on Coherent 3.2 too) of the CRC hash function from: https://www.cs.hmc.edu/~geoff/classes/hmc.cs070.200101/homework10/hashfuncs.html
And the modulus should be a prime number (I choose 503).
Just for comparison: following are the symtab chain lengths for the old and new function for two sources with the new modulus:
(Does this do anything good... all assemblies finish …
=> z80asm: New hash function and use prime modulus

doc/README-asm.txt, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80aout.c
You never know what stuff people will be feeding the assembler.
1. Skip any characters over the 128 character line limit.
=> z80asm: handle some corner cases, add source line limit documentation

z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. Shuffle around the "register" declarations to make sense for the old MWC Coherent 8086 (2 register vars) & 386 (3 register vars) compilers. Modern compilers seem to ignore these anyway when optimizing, for example, if I compile z80asm with "gcc -Dregister=" I got exactly the same object code.
2. Make btoh() register friendly.
This saved 254 bytes of object code and makes the assembler probably a bit faster by using less memory oriented opcodes on Coherent 3.2.
=> z80asm: make proper use of "register" for old compilers

z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80anum.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. Fix memory leak detected by the clang static analyzer in op_irp().
2. Get rid of goto's.
3. Abort op_local() and op_macro() on error.
4. Move local label generation into expn_add_loc() and don't increase mac_loc_cnt if it reached its limit.
5. Use FALSE/TRUE for flags.
6. Some clean up
This commit started so simple: the clang static analyzer found a possible memory leak in op_irp().
Just a small fix involving a goto block... looked real ugly. Got rid of all goto's... and so forth...
=> z80asm: fix memory leak, no goto's, FALSE/TRUE for flags, misc stuff

altairsim/srcsim/memory.c, cpmsim/srcsim/iosim.c, cromemcosim/srcsim/memory.c, frontpanel/lp_gfx.cpp, frontpanel/lp_utils.cpp, frontpanel/lpanel.cpp, imsaisim/srcsim/memory.c, iodevices/apu/am9511.c, iodevices/cromemco-hal.c, iodevices/cromemco-wdi.c, iodevices/generic-at-modem.c, mosteksim/srcsim/config.c, webfrontend/netsrv.c, z80core/sim0.c, z80core/simfun.c
I used the clang static analyzer over the entire project, and it found some problems. Mostly nothing dangerous, except 4.
1. It really didn't like load_hex() in simfun.c since it didn't check that the characters are hexadecimal digits. I rewrote it to check for all things that could possible be wrong with HEX files.
2. While at it, changed load_mos() to use buffered I/O and add an error check in load_file(). Also changed save_core() and load_core() to use buffered I/O and added an error check.
3. pfn in init_memory() in altairsim/cromemcosim/imsaisim was initialized and immediately overwritten. Removed initialization.
4. frontpanel Lpanel::growAlphaObjects was freeing the wrong object.
5. frontpanel Lpanel::readConfig wasn't freeing fname after failure of opening the config file.
6. …
=> fix problems found by clang static analyzer, load_hex(), LOG() uses

z80asm/z80aout.c
Make cary_cnt a WORD. Breaks when code is larger than 65535 bytes... but shouldn't happen, or?
=> z80asm: unconstify C array output and also print out load and start addresses

z80core/simice.c
Just exit the loop on fgets(3) error interpreting it as quit.
=> z80core: fix ice_cmd_loop endless loop when typing ctrl-d (EOF)

z80asm/z80arfun.c
People like assembling disassembler output (like z80sim/z80dis.asm :-)), which print IX/IY offsets as +unsigned, when there are really two-complement signed bytes.
I checked with M80, which also accepts -256..255 as offsets.
=> z80asm: accept -256..255 as IX/IY offset

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/picosim.c, picosim/sim.h, z80core/simcore.c, z80core/simcore.h, z80core/simfun.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
The *nix systems use do_sleep_ms() from sim_fun.c for SLEEP_MS(). The Pico uses its native sleep_ms() SDK function.
time_diff() is used by the core simulator code.
=> Move SLEEP_MS() to sim.h and time_diff() to simcore.c

altairsim/srcsim/sim.h, cpmsim/srcsim/memory.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/sim.h, z80asm/COPYING, z80asm/z80a.h, z80core/sim8080.c, z80core/simcore.c, z80core/simcore.h, z80core/simdis.c, z80core/simglb.c, z80core/simglb.h, z80core/simice.c, z80core/simmain.c, z80core/simz80-cb.c, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c, z80core/simz80.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
Rename Z80_UNDOC to UNDOC_INST. Change sim8080.c to handle undocumented instructions like simz80*.c
Make EXCLUDE_(I8080|Z80) a fully implemented feature.
Now EXCLUDE_I8080 or EXCLUDE_Z80 will completely remove support for the excluded CPU type.
Make save_core()/load_core() save/load core.z80 or core.8080 depending on the CPU type.
Fix ICE "x" command, which accepted "a'" and "f'" for the 8080.
z80asm: fix "#if"
Removed Didier Derny from z80asm/COPYING since z80anum.c was essentially a total rewrite. The only function that looks like the old code is init_ctype().
Right or wrong, what do you think?
=> Tidy-up undocumented instruction support, add full EXCLUDE_* support

cpmsim/srccpm2/Makefile, cpmsim/srccpm2/putsys.c, cpmsim/srccpm3/putsys.c, cpmsim/srcmpm/putsys.c, cpmsim/srctools/cpmrecv.c, cpmsim/srctools/cpmsend.c, cpmsim/srctools/mkdskimg.c, cpmsim/srctools/ptp2bin.c, cpmsim/srcucsd-iv/putsys.c, imsaisim/srcucsd-iv/putsys.c
Ubuntu 24.04 gcc was complaining about unchecked return values from read() and write().
Change srccpm2 putsys.c to not use Mostek binary files as input, like the srccpm3, srcmpm, and srcucsd-iv putsys.c.
Adjust srccpm2 Makefile accordingly.
It just occurred to me: Aren't cpmrecv and cpmsend superseded by "r.com" and "w.com" from Mike Douglas?
Should they perhaps be removed?
=> improve error handling in tools

altairsim/srcsim/config.c, cromemcosim/srcsim/config.c, imsaisim/srcsim/config.c, iodevices/mostek-fdc.c, mosteksim/srcsim/config.c
gcc 14 static analyzer on Ubuntu 24.04 complained about possible NULL return values from strtok().
Removed unnecessary "goto"s and empty statements.
Removed "system.conf:" from LOG because the output already contains the tag "config:",
also it wasn't present in all LOG statements.
=> fix unchecked strtok() return values in config file parsing

altairsim/srcsim/simctl.c, cpmsim/srcsim/iosim.c, cromemcosim/srcsim/simctl.c, imsaisim/srcsim/simctl.c, iodevices/altair-88-2sio.c, iodevices/altair-88-dcdd.c, iodevices/altair-88-sio.c, iodevices/cromemco-hal.c, iodevices/generic-at-modem.c, iodevices/imsai-hal.c, iodevices/mostek-cpu.c, iodevices/unix_network.c, iodevices/unix_terminal.c, z80core/simfun.c, z80core/simint.c, z80core/simmain.c
simmain.c: Don't ignore fread/fwrite results in load_core/save_core.
simint.c: Call reset_unix_terminal since old_term only exists there.
Don't read/write disk file when lseek fails in altair-88-dcdd.c
In the other cases I just added LOGE calls so we at least will know that something went wrong.
Always use fileno(stdin) or fileno(stdout) instead of 0 or 1, since you never know if they weren't freopen()'d.
=> Clean-up ignored return values and some other small stuff

cpmsim/srcsim/iosim.c, iodevices/unix_network.c
Use mkfifo instead of the old mknod.
Use POSIX AF_* in socket calls.
Use getaddrinfo instead of the deprecated gethostbyname.
Use O_ASYNC instead of the old BSDism FASYNC.
=> modernize network code

frontpanel/lp_utils.cpp, iodevices/altair-88-2sio.c, iodevices/altair-88-sio.c, iodevices/cromemco-88ccc.c, iodevices/cromemco-dazzler.c, iodevices/generic-at-modem.c, iodevices/imsai-sio2.c, iodevices/imsai-vio.c, iodevices/proctec-vdm.c, z80core/sim8080.c, z80core/simcore.c, z80core/simmain.c, z80core/simz80.c
This reverts commit 74f6c8507db22e522f545752de892be1218f89f7.
Raspberry Pi Pico SDK does only support gettimeofday...
=> Revert "modernize time code"

cpmsim/srcsim/iosim.c, z80core/sim8080.c, z80core/simglb.c, z80core/simglb.h, z80core/simz80.c
Make busy_loop_cnt an int. Isn't used by anything else. Add time waiting on console input to cpu_start.
=> attempt to fix CPU speed reporting by cpmsim

altairsim/srcsim/sim.h, altairsim/srcsim/simctl.c, cpmsim/srcsim/iosim.c, cpmsim/srcsim/sim.h, cpmsim/srcsim/simctl.c, cromemcosim/srcsim/sim.h, cromemcosim/srcsim/simctl.c, frontpanel/lp_utils.cpp, imsaisim/srcsim/sim.h, imsaisim/srcsim/simctl.c, iodevices/altair-88-2sio.c, iodevices/altair-88-sio.c, iodevices/cromemco-88ccc.c, iodevices/cromemco-dazzler.c, iodevices/generic-at-modem.c, iodevices/imsai-sio2.c, iodevices/imsai-vio.c, iodevices/proctec-vdm.c, mosteksim/srcsim/sim.h, picosim/picosim.c, z80core/sim8080.c, z80core/simcore.c, z80core/simfun.c, z80core/simmain.c, z80core/simz80.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
Use clock_gettime instead of gettimeofday.
Convert get_millis in simfun.c to get_clock_us and use it everywhere.
Add get_clock_us implementation to picosim.
Rename do_sleep_ms back to sleep_ms.
Remove now unneeded time_diff* functions.
=> modernize time code (2nd attempt)

altairsim/srcsim/iosim.c, cpmsim/srcsim/iosim.c, cromemcosim/srcsim/iosim.c, imsaisim/srcsim/iosim.c, z80core/sim8080.c, z80core/simcore.c, z80core/simcore.h, z80core/simice.c, z80core/simmain.c, z80core/simz80.c
uses bit 4 (8080) and bit 5 (Z80) of the hardware control port
init_cpu(): initialize registers independent of current CPU type
reset_cpu(): reset state independent of current CPU type
switch_cpu(): new function to switch CPU type and set cpu_state to new state MODEL_SWITCH
run_cpu(): keep running when cpu_state is MODEL_SWITCH
added h_cpu to history buffer to record CPU type
EXCLUDE_* defines: even more hardcore (don't define Z80 or I8080) fixed a few cases where a CPU type value was used that isn't available
Appended are the changes I made to ex.mac to test this.
But the thing is ex.mac completely fails in 8080 mode... (i.e. when assembled with "exkind = 0").
It also doesn't work with z80pack 1.37.
```
; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
; modifications by Peter …
```
=> implement runtime switchable CPU type

iodevices/simbdos.c
I found it always annoying that the file names from 'R' and 'W' were upper case.
Doesn't make a difference on case insensitive file systems like on Windows or macOS (except for looks).
=> simbdos: convert file names to lower case

z80core/sim8080.c
You can now emulate an AMD 8080 CPU if you so desire.
8080ex.com checksums match the ones shown on
https://web.archive.org/web/20151108135453/http://www.idb.me.uk/sunhillow/8080.html
=> add AMD 8080 support

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/sim.h, z80core/sim8080.c, z80core/simcore.c, z80core/simglb.c, z80core/simglb.h, z80core/simz80-cb.c, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c, z80core/simz80.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
All behind the new UNDOC_FLAGS define.
Passes EVERY test from https://github.com/raxoft/z80test and of course ex.mac assembled with exkind=2.
Modifications to existing code kept to a minimum:
Needed to split of the address calculation from memrdr calls in some instructions.
Changed conditional JP/JR/DJNZ/CALL instructions to always fetch the destination address/offset as a real CPU does. Did the same for sim8080.
Some small cosmetic changes.
Additional references:
http://www.grimware.org/lib/exe/fetch.php/documentations/devices/z80/z80.memptr.eng.txt https://github.com/hoglet67/Z80Decoder/wiki/Undocumented-Flags
=> make z80core behave like a Zilog/Mostek NMOS Z80 as far as I can do

z80core/sim8080.c, z80core/simglb.c, z80core/simglb.h, z80core/simice.c, z80core/simz80.c
Things found when compiling with "-fsanitize=undefined".
t T-State counter overflowed without f_flag.
ADD A,A and ADC A,A used undefined signed left shift.
changed code to use only one T-counter (T).
=> one counter to rule them all

Makefile, cpmsim/srccpm2/Makefile, cpmsim/srccpm3/Makefile, cpmsim/srcmpm/Makefile, cpmsim/srctools/Makefile, cpmsim/srcucsd-iv/Makefile, cpmtools/Makefile, imsaisim/srcucsd-iv/Makefile, picosim/src-examples/Makefile, z80asm/Makefile, z80core/sim8080.c, z80sim/Makefile
So you can build everything without having to install anything from z80pack.
move trap_undoc declaration to where it is in the z80 files.
=> use in-tree z80asm for building and use "install" for installing files

cpmsim/srcsim/Makefile, cpmsim/srcsim/iosim.c
cpmsim and iodevices/unix_network.c already create these automatically.
Change "./cpmrecv" to "./srctools/cpmrecv" so one can run cpmsim without installing the tools in srctools.
I can't see a scenario where cpmrecv would be in .
=> remove directory/pipes creation from makefile

Makefile, altairsim/srcsim/Makefile, altairsim/srcsim/simctl.c, cpmsim/srccpm2/Makefile, cpmsim/srccpm3/Makefile, cpmsim/srcmpm/Makefile, cpmsim/srcsim/Makefile, cpmsim/srctools/Makefile, cpmsim/srcucsd-iv/Makefile, cpmtools/Makefile, cromemcosim/srcsim/Makefile, cromemcosim/srcsim/simctl.c, frontpanel/Makefile, imsaisim/srcsim/Makefile, imsaisim/srcsim/simctl.c, imsaisim/srcucsd-iv/Makefile, mosteksim/srcsim/Makefile, picosim/src-examples/Makefile, webfrontend/civetweb/Makefile, z80asm/Makefile, z80core/simice.c, z80sim/Makefile, z80sim/srcsim/Makefile
Tweaked program name shown by 's' ICE command.
Avoid compiler warning when building with FRONTPANEL=NO.
Renamed allclean to distclean (more standard).
Force visit to z80asm directory.
Working toward proper "make install/uninstall" (not done yet).
Setup and use CPPFLAGS.
Split link options in LDFLAGS and LDLIBS.
Redid frontpanel and civetweb library rules ("-lfrontpanel:" looked just strange to me).
=> a small change, avoid compiler warnings, and Makefile tweaks

cromemcosim/conf_2d/system.conf, cromemcosim/conf_3d/system.conf, cromemcosim/srcsim/Makefile, cromemcosim/srcsim/config.c, cromemcosim/srcsim/iosim.c, cromemcosim/srcsim/sim.h, cromemcosim/srcsim/simctl.c, imsaisim/conf_2d/system.conf, imsaisim/conf_3d/system.conf, imsaisim/srcsim/Makefile, imsaisim/srcsim/config.c, imsaisim/srcsim/iosim.c, imsaisim/srcsim/sim.h, imsaisim/srcsim/simctl.c, iodevices/cromemco-88ccc.c, iodevices/cromemco-d+7a.c, iodevices/cromemco-dazzler.c, iodevices/cromemco-hal.c, iodevices/cromemco-tu-art.c, iodevices/imsai-hal.c, iodevices/imsai-vio.c, webfrontend/netsrv.c, webfrontend/netsrv.h, z80core/simglb.c, z80core/simglb.h, z80core/simmain.c
When the web-based frontend code is compiled in, it can now be enabled at runtime with the new option -n.
Default port number is set in sim.h, but it can be changed with a new configuration file option "ns_port".
Added SYSDOCROOT define to Makefile. This directory will be used when ../../webfrontend/www/<machine> can't be found.
=> make web-based frontend a runtime opt-in feature

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/sim.h, z80core/sim8080-00.c, z80core/sim8080.c, z80core/simcore.h, z80core/simglb.c, z80core/simglb.h, z80core/simz80-00.c, z80core/simz80-cb.c, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c, z80core/simz80.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
Seperated big switch and flag tables into two options: INSTR_SWTCH and FLAG_TABLES
Add more option defines checking in simcore.h
Fixed a cut & paste error in simz80-fdcb.c: trap_ddcb -> trap_fdcb
=> implemented flag tables for the Z80 like the 8080

cpmtools/Makefile, cpmtools/ex.mac, z80asm/z80aout.c
Change error message.
"invalid expression in option -d: invalid expression" looks silly.
=> use new -d syntax

z80core/sim8080-00.c, z80core/sim8080.c, z80core/simice.c, z80core/simz80-00.c
New DAA implementation, much cleaner
Produces exactly the same output (A, H, and C) for all 2048 combinations of A, N-FLAG, H-FLAG, and C_FLAG as the one from Mark Garlanger.
=> ICE timing option for 'g' and new DAA implementation

mosteksim/srcsim/simctl.c, z80core/simice.c
The CPU timing is really inaccurate with console I/O going on.
Perhaps add get_clock_us() calls to io_in() and io_out() to subtract all I/O time,
but get_clock_us() is relatively costly on *nix.
=> run CPU with timing in ice_cmd_lop when go_flag is 2

z80core/sim8080.c, z80core/simz80.c
Make the description clearer.
Follow z80core conventions: All flags are explicitly set and cleared.
=> Clean-up DAA

cpmtools/ex.mac
The ld8im test was writing inside the exercisers code/tables. Found by running it two times on z80sim in bare machine mode.
Patches sent to Peter Schorn.
=> fixed self destroying problem in ex.mac

z80core/alt8080.h, z80core/simz80.c
Forgot int_protection in alt8080 EI.
Restore T-states in RET C in simz80.c broken in unmessify commit.
=> fix errors

z80core/altz80.h, z80core/simcore.h, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c, z80core/simz80.c
Overlooked (signed char) type casts during integer type conversion.
=> define SBYTE and use it, like SWORD used for ADC/SBC HL

intelmdssim/README, intelmdssim/srcsim/iosim.c, intelmdssim/srcsim/simctl.c, iodevices/mds-isbc202.c, iodevices/mds-monitor.c
Document from where the monitor sources originated.
Add an RTC mutex.
Add a disk ready check to isbc202_reset() so you can start the machine with no disk images and get to the monitor.
=> intelmds: monitor sources origin, RTC mutex, disk ready check

intelmdssim/srcsim/iosim.c, iodevices/mds-isbc202.c, iodevices/mds-isbc202.h
Checks every second if disk image files have vanished or appeared.
Since ISIS doesn't use an interrupt handler for disk I/O, one can use the INT 2 LED to ones advantage:
To change a disk, remove the disk image file, wait for the INT 2 LED to go on, than put the new disk file in place.
To format a new disk image file in an empty drive use "touch drive[abcd].dsk", wait for the INT 2 LED, then use the ISIS "format" command.
=> intelmds: implement disk change detection logic

doc/README-asm.txt, z80asm/z80amfun.c
Don't complain about undelimited strings.
Now you can use "EX AF,AF'" inside macros, yeah!
Don't check for balanced angel brackets.
This was only done the aid the detection of comments starting with a double comment character, which are excluded in the listing of expanded macros.
z80asm now behaves like m80, which also just cuts at any ";;" outside a string.
The previous change allows the assembly of diskdef.lib, which is used by the Intel MDS CP/M BIOS, with z80asm.
=> z80asm: relax macro parameter substitution parsing

intelmdssim/README, iodevices/mds-isbc201.c, iodevices/mds-isbc202.c, iodevices/mds-isbc206.c
hdcopy works by formatting 4 tracks, copy them, and repeat.
This didn't work because the format track emulation would create a new disk image file when formatting track 0 and the write emulation checks that the disk image file has the full size.
Add an ftruncate to make the file full size when formatting track 0.
Also expand description of what is emulated in the README.
=> intelmds: make ISIS hdcopy work

doc/README-asm.txt, z80asm/z80aout.c
Tested with MSYS2 under Windows 10 assembling microchess.
=> z80asm: make C output work on systems with use CRLF.

altairsim/srcsim/iosim.c, altairsim/srcsim/memsim.h, altairsim/srcsim/simctl.c, cpmsim/srcsim/iosim.c, cpmsim/srcsim/memsim.h, cromemcosim/srcsim/iosim.c, cromemcosim/srcsim/memsim.h, cromemcosim/srcsim/simctl.c, imsaisim/srcsim/iosim.c, imsaisim/srcsim/memsim.h, imsaisim/srcsim/simctl.c, intelmdssim/srcsim/iosim.c, intelmdssim/srcsim/memsim.h, mosteksim/srcsim/iosim.c, mosteksim/srcsim/memsim.h, picosim/iosim.c, picosim/memsim.h, z80core/simcore.c, z80sim/srcsim/iosim.c, z80sim/srcsim/memsim.h
Mostly reverts d7f4eea85b.
Add IO_DATA_UNUSED to define the value returned by unused I/O ports (only really used by intelmdssim, which returns 0x00).
I would really like to clean things up, and move all the `extern` 's and definitions into header files, which then defines the interface of the corresponding `.c` file. This convention is already followed by `iodevices`. Opinions?
=> make port_in/port_out const arrays of pointers

iodevices/mds-isbc201.c, iodevices/mds-isbc202.c, iodevices/mds-isbc206.c
Noticed this during testing when I did my monster clean-up.
The emulator has all three disk controllers (SD, DD, HD) attached. When ISIS boots it configures itself on the present bits returned by the controllers, and since all three controllers set the present bit, ISIS always configured itself for a hard drive system, and if you only had drivea.dsk (= DD unit 0) in the disks directory, you couldn't do anything, since ISIS tried to access the not available drivei.dsk as the system disk (HD unit 0 = F0), and always shows error 30 (drive not ready).
Changed the reset logic of the controllers to no set the present bit when no disk images are available.
Now you need to have at least one disk image (or two HD images) in the disks directory on startup for each controller you want to use.
=> intelmds: change controller present logic on reset

intelmdssim/isisii43, iodevices/mds-isbc201.c, iodevices/mds-isbc202.c, iodevices/mds-isbc206.c
This mostly reverts 075c9ad574.
Set present bit of disk controllers to 0 if "ISBC20[126]_OFF" environment variables are set.
Allows running a floppy only ISIS when the HD controller is enabled in sim.h.
Use this in the "isisii43" script.
=> intelmds: add environment convenience variables for disk controllers

z80asm/Makefile, z80asm/z80a.h, z80asm/z80aglb.c, z80asm/z80aglb.h, z80asm/z80amain.c, z80asm/z80amain.h, z80asm/z80amfun.c, z80asm/z80amfun.h, z80asm/z80anum.c, z80asm/z80anum.h, z80asm/z80aopc.c, z80asm/z80aopc.h, z80asm/z80aout.c, z80asm/z80aout.h, z80asm/z80apfun.c, z80asm/z80apfun.h, z80asm/z80arfun.c, z80asm/z80arfun.h, z80asm/z80atab.c, z80asm/z80atab.h
Still compiles on Coherent 3.2 and 4.2, and also compiles and runs on 2.11BSD PL481 on a PDP-11.
=> z80asm: use interface header files

.github/workflows/makefile-ubuntu.yml, .github/workflows/makefile.yml, .gitignore, Makefile, README.md
Wrote an initial README.md with sample CP/M 2.2 and 3 runs, and enabled github actions for Ubuntu building the sources and creating an artifact with the result.
z80sim had to be disabled as it appears its sim.h does not compile with this toolchain.
=> Added README.md and GitHub Action building under Ubuntu 

picosim/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/.gitignore
So that no-OS-FatFS-SD-SDIO-SPI-RPi-Pico is a clean copy of the 2.3.2 release, except for pico-sdk 2.0.0 changes.
=> add back lost no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/.gitignore

picosim/rp2040/CMakeLists.txt, picosim/rp2040/stdio_msc_usb/include/stdio_msc_usb.h, picosim/rp2040/stdio_msc_usb/reset_interface.c, picosim/rp2040/stdio_msc_usb/stdio_msc_usb_descriptors.c, picosim/rp2350/CMakeLists.txt.arm, picosim/rp2350/CMakeLists.txt.corev, picosim/rp2350/stdio_msc_usb/include/stdio_msc_usb.h, picosim/rp2350/stdio_msc_usb/reset_interface.c, picosim/rp2350/stdio_msc_usb/stdio_msc_usb_descriptors.c
BTW, I've ordered a [RP2350-GEEK](https://www.waveshare.com/rp2350-geek.htm) at [Amazon](https://www.amazon.de/Waveshare-RP2350-GEEK-Development-Microcontroller-Downloader/dp/B0DNFHZPGX). Should be here in 2 weeks.
I've started porting FatFS to RISC-V, it compiles, but I can't test it, since I don't have a RP2350 board yet. Can you test my [riscv-fatfs](https://github.com/sneakywumpus/z80pack/tree/riscv-fatfs) z80pack branch on your Pico 2?
=> sync with SDK 2.1.0 pico_stdio_usb, move USB manu/prod to CMakeLists.txt

picosim/rp2350/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/src/CMakeLists.txt, picosim/rp2350/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/src/include/delays.h, picosim/rp2350/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/src/include/util.h, picosim/rp2350/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/src/sd_driver/SDIO/rp2040_sdio.c, picosim/rp2350/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/src/src/crash.c, picosim/rp2350/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico/src/src/my_debug.c
rp2040_sdio.c(rp2040_sdio_tx_poll): I think there is no way to determine if we are in an interrupt/exception-handler on RISC-V, therefore only do this on ARM.
crash.c(reset): Use watchdog_reboot() instead of CMSIS NVIC_SystemReset().
crash.c: exclude ARM specific DebugMon_Handler()/isr_hardfault() on RISC-V.
=> no-OS-FatFS-SD-SDIO-SPI-RPi-Pico: use Pico SDK API's instead of ARM CMSIS ones

z80core/simdis.c
before:
0010 - 10 E0            DJNZ    FFFFFFF2
fff0 - 10 20            DJNZ    10012
now:
0010 - 10 E0            DJNZ    FFF2
fff0 - 10 20            DJNZ    0012
=> fix relative jump address wrap-around disassembly

z80core/simdis.c
Wouldn't flag operand-less undocumented DD/FD opcodes. DD/FD followed by DD/FD is an undocumented NOP.
Should now produce sensible output for every random byte stream.
before:
```
0000 - DD 37            SCF
0002 - DD FD
0004 - DD               NOP*
0005 - ED 45            RETN
0007 - DD 11 F1 0C      LD*     DE,0CF1
```
now:
```
0000 - DD 37            SCF*
0002 - DD               NOP*
0003 - FD               NOP*
0004 - DD               NOP*
0005 - ED 45            RETN
0007 - DD 11 F1 0C      LD*     DE,0CF1
```
Bloody undocumented instructions... but who am I to complain, I started it...
Output numeric operands in assembler hex notation to make it easier to convert disassembler output into something that the assembler accepts.
=> simdis: fix undocumented opcode disassembly and increase assemblability of output

.github/workflows/makefile-ubuntu.yml
Got github mails with build failures when you pushed to master and I synced my repo. Must to related to the Ubuntu 24.04 update. Hope this fixes that.
=> add jpeg dependency to Ubuntu github action

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, intelmdssim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/srcsim/sim.h, picosim/srcsim/simmem.h, z80core/simdefs.h, z80core/simice.c, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast, z80sim/srcsim/simmem.h
Guard FAST_BLOCK by !EXCLUDE_Z80.
Remove unneeded checks from simdefs.h (already guarded in sim.h).
simice: clean-up optional features messages.
Add hardware breakpoint support to picosim, so we can test performance impact.
Or we could switch from the "See what you are missing" paradigm and remove the not enabled commands entirely from the ICE. Thoughts?
=> clean-ups & picosim hardware breakpoint support

picosim/srcsim/simmem.h, z80core/simice.c
uninstall_softbp() was in the wrong place, would lead to loss of original instruction...
=> fix single step software breakpoint handling

doc/README-ice.txt, picosim/srcsim/sim.h, z80core/log.h, z80core/simcore.c, z80core/simice.c
Make log.h usable in picosim and more robust.
Use `PRIu32` in _log_timestamp().
Encapsulate `LOG?()` in `do { ... } while (0)` so that they work correctly with statements like:
```
if (foo)
LOGW(TAG, "...");
else
bar();
```
Use `LOG?` everywhere and make `BAREMETAL` an ICE only options.
Add i_flag/u_flag toggle commands to the ICE. Also report CPU errors in 'p' command. Clean-up 's' command a bit.
=> log.h and ICE 'i' and 'u' commands

altairsim/srcsim/Makefile, cpmsim/srcsim/Makefile, cromemcosim/srcsim/Makefile, frontpanel/Makefile, frontpanel/jpeg.c, frontpanel/jpeg.h, frontpanel/lp_window.c, imsaisim/srcsim/Makefile, intelmdssim/srcsim/Makefile, mosteksim/srcsim/Makefile, picosim/srcsim/CMakeLists.txt, z80core/simsdl.c, z80core/simsdl.h, z80sim/srcsim/Makefile
Fixed native MS Windows compilation of the frontpanel library after the C conversion. Can't test if it works, but the code-flow didn't change with the C conversion, so it should. Used MSYS2 with mingw-w64-ucrt-x86_64-gcc on my Windows 11 VM to check that it compiles.
=> compile {non-}SDL files conditionally, fix native MS Windows compilation

frontpanel/lp_main.c, frontpanel/lp_window.c, frontpanel/lpanel.c, frontpanel/lpanel.h
The swap buffer calls where made with the data lock mutexes held, this caused fp_sampleData() to be blocked until the next VSync on macOS and Linux using NVIDIA graphics, which is obviously not what we want.
=> move swap buffer calls outside of Lpanel_draw()

altairsim/srcsim/simcfg.c, cpmsim/srcsim/simio.c, cpmsim/srcsim/simmem.h, cpmsim/srctools/bin2hex.c, cpmsim/srctools/mkdskimg.c, cromemcosim/srcsim/simcfg.c, cromemcosim/srcsim/simctl.c, frontpanel/jpeg.c, frontpanel/lp_gfx.c, frontpanel/lp_utils.c, frontpanel/lpanel.c, imsaisim/srcsim/simcfg.c, imsaisim/srcsim/simctl.c, intelmdssim/srcsim/simcfg.c, intelmdssim/srcsim/simctl.c, iodevices/altair-88-dcdd.c, iodevices/cromemco-fdc.c, iodevices/mostek-fdc.c, iodevices/sd-fdc.c, iodevices/tarbell_fdc.c, mosteksim/srcsim/simcfg.c, picosim/srcsim/disks.c, webfrontend/netsrv.c, z80core/simmain.c
altairsim/srcsim/simcfg.c,
cpmsim/srcsim/simio.c,
cromemcosim/srcsim/simcfg.c,
imsaisim/srcsim/simcfg.c,
intelmdssim/srcsim/simcfg.c,
mosteksim/srcsim/simcfg.c:
Changed
```
s = buf;
while (fgets(s, BUFSIZE, ...)) {
```
to
```
while (fget(buf, BUFSIZE, ...)) {
s = buf;
```
since s was sometimes manipulated inside the loop.
cpmsim/srcsim/simmem.h:
Changed memrdr to match memwrt, no functional change. Analyzer complained about a useless assignment.
cpmsim/srctools/bin2hex.c,
cpmsim/srctools/mkdskimg.c,
frontpanel/jpeg.c:
Unclosed files, also reformatted bin2hex.c.
z80core/simmain.c:
Re-did save_core and load_core since the analyzer complained about unchecked errors.
iodevices/altair-88-dcdd.c:
Renamed dsk_check to dsk_open and leave file open on success. Analyzer complained about possible …
=> clang 19 static analyzer run & clean-up

iodevices/cromemco-88ccc.c, iodevices/cromemco-88ccc.h, iodevices/cromemco-d+7a.c, iodevices/cromemco-d+7a.h, iodevices/cromemco-dazzler.c, iodevices/cromemco-hal.c, iodevices/cromemco-hal.h, iodevices/cromemco-wdi.c, iodevices/diskmanager.c, iodevices/generic-at-modem.c, iodevices/generic-at-modem.h, iodevices/imsai-hal.c, iodevices/imsai-hal.h, iodevices/imsai-sio2.c, iodevices/imsai-vio.c, webfrontend/netsrv.c, webfrontend/netsrv.h
Re-format David McNaughton's code in project style, max 100 chars. Also some by-Hand formatting. Verified generated object code stayed the same.
Boolify David McNaughton's code and clean-up netsrv.[ch]. Moved types only used in netsrv.c from netsrv.h to netsrv.c. Made internal functions/variables of netsrv.c static.
Move system includes not needed in netsrv.h to netsrv.c. This revealed that cromemco-dazzler and imsai-vio need to include string.h with HAS_NETSERVER.
At least on Linux the first message queue created has an id of 0, this tripped up the code which expected a value > 0. Use -1 to mean no queue connected and not 0.
The manual page of msgget(2) also states that the returned id is a non-negative integer, so 0 is a completely legal value.
=> Re-format, boolify, fix message queue id bug in David McNaughton's code

z80core/sim8080.c, z80core/simpanel.c, z80core/simz80.c
Left/Right changes base address by 1.
Up/Down by 16.
Page Up/Page Down by 256.
Begin rounds down to xxx0.
End rounds up to xxx0.
Shift multiplies/rounding change by 16.
Mouse wheel works too.
Also move "leave" label back. My Mac compiler didn't like it.
=> add some keyboard/mouse controls to change memory display base address

altairsim/srcsim/simctl.c, z80core/simcore.c, z80core/simdefs.h, z80core/simglb.c, z80core/simglb.h, z80core/simpanel.c
Adds buttons to switch between memory and ports display. Sticky button in ports display makes the port lights sticky, so one can see all the ports accessed in a code run.
=> add I/O ports view to introspection panel
