udo-munk/z80pack

imsaisim/srcsim/iosim.c, imsaisim/srcsim/sim.h, imsaisim/srcsim/simctl.c
This also includes some defines that help isolate code &/or features that impact readability and help with porting to microcontrollers
=> Continued isolation of h/w control from simctl.c to iosim.c

webfrontend/www/imsai/index.html
Forgot a file in the web UI. Just an automatic redirect from `http://localhost:8080` to `http://localhost:8080/console` to start things smoothly.
Ref #38
=> Forgot this file.

iodevices/cromemco-dazzler.c, webfrontend/netsrv.c, webfrontend/netsrv.h
This is the server side additions for Cromemco Dazzle support in the web UI.
As mentioned in #38
=> Added: netsrv support for cromemco dazzler

imsaisim/srcsim/GNUmakefile, iodevices/generic-at-modem.c, iodevices/imsai-sio2.c, iodevices/libtelnet.c, iodevices/libtelnet.h
Changes and instructions will be included in #66 so they don't get hidden when/if the PR is accepted.
=> Added: telnet handler to generic-at-modem

imsaisim/conf_2d/boot.conf, imsaisim/conf_3d/boot.conf, imsaisim/cpm22, imsaisim/srcsim/iosim.c, imsaisim/srcsim/sim.h, iodevices/COPYING, iodevices/generic-at-modem.c, iodevices/generic-at-modem.h, iodevices/imsai-sio2.c, iodevices/imsai-sio2.h
The main change here is updating the **generic-at-modem** with the latest functionality, see: [IMSAI8080esp - July 2021 Release](https://github.com/thehighnibble/firmware/releases/tag/v1.7.0) for details.
A number of copyright notices have been updated to 2021
To support easily setting the `MODEM.init` environment variable a new configuration file has been added:  `conf/boot.conf`
The startup script `cpm22` has been updated to parse and process this file into the environment before running `imsaisim`
=> Update: AT-Modem to latest functionality

z80core/simfun.c
=> fix range check

z80asm/z80anum.c
T_NOOPR is a symbol, make that clear.
Use isxdigit, otherwise ? and @ would be accepted as digits 8 and 9,
and %, and . as digits -11 and -2...
=> z80asm: rename T_NOOPR to T_SYM and use isxdigit for digits

doc/README-asm.txt, z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80anum-old.c, z80asm/z80anum-orig.c, z80asm/z80anum.c, z80asm/z80aopc.c, z80asm/z80aout.c, z80asm/z80apfun.c, z80asm/z80arfun.c, z80asm/z80atab.c
1. Added a helper function for parsing, so that DEFB, DEFW, IFEQ, IFNEQ and machine instructions now work with expressions containing ',' char constants
2. Split IF* and ELSE,ENDIF processing to make the IF* processing cleaner
3. Added rest of IF* pseudo-ops.
4. Converted opcode/operand type to flags. Added OP_NOPRE for pseudo-ops who process the operand on their own.
5. Removed TYPE, the implementation was totally wrong and it doesn't make much sense in an absolute mode only assembler.
6. NUL now works... If NUL is defined as a symbol, it won't work anymore as a unary operator, it's just too special.
6. Moved LABSEP check and label overflow processing to get_label(). I can't understand why it was in get_opcode().
7. Treat '\n' as white space, except inside strings.
8. Added NULL check to …
=> z80asm: IF* pseudo ops, DEF[BW],IFEQ & instructions argument parsing, clean ups

z80asm/z80anum.c
NUL was still not right. Hopefully now...
Readded TYPE. I'm not sure if it is completely right.
```
LOC   OBJECT CODE   LINE   STMT SOURCE CODE
1      1 	IF	NUL
0000  af               2      2 	XOR	A
3      3 	ENDIF
4      4 	IF	NUL ABC
5      5 	XOR	A
6      6 	ENDIF
7      7 	IF	(5 == 4) AND NOT NUL A
8      8 	XOR	A
9      9 	ENDIF
10     10 	IF	(5 == 5) AND NOT NUL B
0001  af              11     11 A:	XOR	A
12     12 	ENDIF
007b                  13     13 AA	DEFL	123
14     14 	IF1
15     15 BB1	DEFL	TYPE A
16     16 CC1	DEFL	TYPE B
17     17 ;FF	DEFL	(TYPE (B + 5) & 20H) EQ 20H
18     18 	ENDIF
19     19 	IF2
0020                  20     20 BB2	DEFL	TYPE A
0020                  21     21 CC2	DEFL	TYPE B
22     22 	ENDIF
ffff                  23     23 DD	DEFL	(TYPE AA & 20H) EQ 20H …
```
=> z80asm: NUL again, TYPE readded

z80core/sim6.c, z80core/sim7.c
Now it compiles with Xcode 14 llvm
=> Fix no UNDOC C++ compile

z80asm/z80a.h, z80asm/z80amain.c
=> z80asm: clean up symbol table sort options

z80asm/z80a.h, z80asm/z80amain.c, z80asm/z80anum.c, z80asm/z80aout.c, z80asm/z80apfun.c
Can't stop doing this...
Must have gone over every line multiple times...
Why do I still find things I don't like...
Ramblings of a mad men :-)
=> z80asm: code clean up

z80asm/z80amain.c
Reorder code to make the similarities of the three if blocks more visible.
=> z80asm: make process_line code clearer

doc/README-cpm.txt, doc/README-ice.txt
Also some fixes to README-cpm.txt
=> Add some documentation for the ICE.

iodevices/cromemco-fdc.c
cpm22 boots, itc-cpm boots, micah-cpm boots, cromix floppy root boots.
Hopefully I have done nothing wrong, please test.
=> cromemco-fdc get_pos rewrite

z80asm/z80amain.c, z80asm/z80amfun.c, z80asm/z80apfun.c
It was late at night as I started this...
=> z80asm: finish FALSE/TRUE use

cpmsim/srccpm2/putsys.c, cpmsim/srccpm3/putsys.c, cpmsim/srcmpm/putsys.c, cpmsim/srctools/mkdskimg.c, cpmsim/srctools/ptp2bin.c
These are all dead assignments.
=> fix rest of clang static analyzer warnings

z80asm/check-asm.sh
I don't know if this is worth being added to the code base. You decide.
=> z80asm: script i use to check if i broke the assembler

HISTORY, altairsim/srcsim/iosim.c, cpmsim/srcsim/iosim.c, cpmsim/srctools/mkdskimg.c, iodevices/cromemco-tu-art.c, iodevices/mostek-fdc.c, z80asm/z80amain.c
Printer code never checked if file creation succeeded.
Moved fork/exec to the beginning of init_io() in cpmsim/srcsim/iosim.c.
=> Small cleanups, stuff complained about by gcc static analyzer

altairsim/srcsim/simctl.c, cpmsim/srcsim/simctl.c, cromemcosim/srcsim/simctl.c, imsaisim/srcsim/simctl.c, z80core/simfun.c, z80core/simice.c
Reduces code duplication.
This makes the ICE CPU error reporting colorful.
=> add report_cpu_error() to simfun.c and use it

z80core/simice.c
I totally forgot about "make MODE=DEV"...
The "ignored return value" compiler messages come with _FORTIFY_SOURCE > 0
Clear the EOF condition when stdin is a TTY.
No more exits with CTRL-D or CTRL-C.
The loop in do_go() looked wrong.
cpu_error could never be 0 to reach the "goto".
Now uses the loop from do_trace(). One "goto" gone...
Remove the "goto" in handle_break() by using a "break" and "if". Another one bites the dust...
Rewrote "do_reg()". Looked boring. Would also be monstrous with the new fgets() return value check and EOF clearing. Looks clever now :-)
=> ICE: fix ignored fgets() return value and other stuff

frontpanel/lp_utils.cpp, iodevices/altair-88-2sio.c, iodevices/altair-88-sio.c, iodevices/cromemco-88ccc.c, iodevices/cromemco-dazzler.c, iodevices/generic-at-modem.c, iodevices/imsai-sio2.c, iodevices/imsai-vio.c, iodevices/proctec-vdm.c, z80core/sim8080.c, z80core/simcore.c, z80core/simmain.c, z80core/simz80.c
Use clock_gettime instead of gettimeofday.
Use nanosleep instead of usleep.
Remove historic comment from time_diff.
=> modernize time code

z80core/sim8080.c, z80core/simcore.c, z80core/simglb.c, z80core/simglb.h, z80core/simice.c, z80core/simz80-ed.c, z80core/simz80.c
Also add R as a register to the ICE.
Existing core files will be incompatible after this change.
=> use T for frequency measuring and make R a BYTE and Z80 only

z80core/sim8080.c, z80core/simz80.c
'T" was missing interrupt cycles and "t" was missing DMA cycles.
=> make clock cycle accounting more accurate

frontpanel/lp_utils.cpp, z80core/simfun.c
=> Use clock_gettime only when _POSIX_TIMERS > 0

z80core/sim8080.c, z80core/simz80-cb.c, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c
trap_* always returns 0 if u_flag is set
=> clean-up trap_* calls

picosim/CMakeLists.txt, picosim/picosim.c, picosim/sim.h, z80core/sim8080.c, z80core/simcore.c, z80core/simfun.c, z80core/simice.c, z80core/simint.c, z80core/simz80.c
Hopefully this makes sense and I didn't break picosim...
Also cleaned up #include's in z80core
Did remove the #ifdef PICO stuff from simcore. Why is this necessary? I have the Pico SDK here and can build picosim without it.
=> make it possible to use the ICE with bare metal simulators

cpmtools/README, cpmtools/sw8080.asm, cpmtools/swz80.asm
Forgot to update the README.
Just return to bdos in sw8080 and swz80.
=> cpmtools: small changes

z80sim/z80test/README.txt, z80sim/z80test/z80sim.patch, z80sim/z80test/z80test.patch
=> add patches and instructions for running z80test

altairsim/srcsim/Makefile, cpmsim/srccpm2/Makefile, cpmsim/srccpm3/Makefile, cpmsim/srcmpm/Makefile, cpmsim/srcsim/Makefile, cpmsim/srctools/Makefile, cpmsim/srcucsd-iv/Makefile, cpmtools/Makefile, cromemcosim/srcsim/Makefile, frontpanel/Makefile, imsaisim/srcsim/Makefile, imsaisim/srcucsd-iv/Makefile, mosteksim/srcsim/Makefile, z80asm/Makefile, z80core/simcore.c, z80sim/Makefile, z80sim/srcsim/Makefile
Stealthily keep z80core/sim* source lines under 80 chars...
=> Makefiles: don't remove things we didn't create in "clean"

.gitignore, picosim/picosim.c, z80core/simcore.c, z80core/simfun.c, z80core/simice.c
Rename term_in to get_cmdline and provide one in sumfun.c. Move the isatty logic there.
Don't output anything in report_cpu_error if cpu_error is NONE.
Add cpmtools/*.{com,lis} to .gitignore
=> ICE input cleanup and other small things

z80core/simdis.c, z80core/simfun.c, z80core/simice.c, z80core/simmain.c
Add CPU switch command to the ICE.
Announce if undocumented flags are maintained or not. Add undocumented flags to ICE register output.
Changed disasm to not modify its argument and just return the length of the instruction.
=> flesh out CPU switching and undocumented flags support

z80core/sim8080.c, z80core/simcore.c, z80core/simcore.h, z80core/simice.c, z80core/simz80-cb.c, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c, z80core/simz80.c
also add comments to the flags and bus status defines
please look at the bus status comments to see that i didn't mess that up.
=> rename N1 & N2 flags to emulator community standard X & Y

cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, webfrontend/netsrv.c, z80core/simmain.c
backspace hack messes up netsrv code
=> just put the USR_CPR on a new line

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/sim.h, z80core/simcore.c, z80core/simice.c
use one define to set up the simulator core for bare metal use.
remove \n from USR_COM in mosteksim
=> change CORE_LOG & ICE_BAREMETAL to just BAREMETAL

Makefile, altairsim/srcsim/Makefile, cpmsim/srcsim/Makefile, cpmsim/srcucsd-iv/Makefile, cromemcosim/srcsim/Makefile, imsaisim/srcsim/Makefile, mosteksim/srcsim/Makefile, webfrontend/civetweb/Makefile, z80sim/srcsim/Makefile
Just installs/uninstalls the binaries for now.
=> Makefile fixes so install/uninstall works at least rudimentally

iodevices/diskmanager.c, iodevices/imsai-fif.c
I tried to name the disk "hd0.hdd" to make it show up as a hard disk drive in the web frontend, but that
didn't work. Maybe the web code needs to be changed?
=> try to get the imsai-fif hd disk to get along with the disk manager

Makefile, altairsim/srcsim/Makefile, cpmsim/srccpm2/Makefile, cpmsim/srccpm3/Makefile, cpmsim/srcmpm/Makefile, cpmsim/srcsim/Makefile, cpmsim/srcucsd-iv/Makefile, cpmtools/Makefile, cromemcosim/srcsim/Makefile, imsaisim/srcsim/Makefile, imsaisim/srcucsd-iv/Makefile, iodevices/imsai-fif.c, mosteksim/srcsim/Makefile, picosim/src-examples/Makefile, z80asm/Makefile, z80sim/Makefile, z80sim/srcsim/Makefile
Rename Z80ASMOPTS to Z80ASMFLAGS.
Remove unused directory variables.
Add installation of web frontend server files.
=> further makefile tweaks, update copyright/history in imsai-fif.c

doc/README-asm.txt, z80asm/z80aglb.c, z80asm/z80amain.c, z80asm/z80aout.c
You can even do stuff like:
-da=3 "-db=a shl 2" -dc=b-a
=> z80asm: add optional expression to option d

altairsim/srcsim/sim.h, cpmsim/srcsim/sim.h, cromemcosim/srcsim/sim.h, imsaisim/srcsim/sim.h, mosteksim/srcsim/sim.h, picosim/sim.h, z80core/alt8080.h, z80core/sim8080.c, z80core/simglb.c, z80core/simglb.h, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
Is this getting messy again or OK?
=> add alternative 8080 simulation optimized for code size

altairsim/srcsim/Makefile, altairsim/srcsim/sim.h, cpmsim/srcsim/Makefile, cpmsim/srcsim/sim.h, cromemcosim/srcsim/Makefile, cromemcosim/srcsim/sim.h, imsaisim/srcsim/Makefile, imsaisim/srcsim/sim.h, mosteksim/srcsim/Makefile, mosteksim/srcsim/sim.h, picosim/sim.h, z80core/alt8080.h, z80core/altz80.h, z80core/log.h, z80core/simcore.h, z80core/simglb.c, z80core/simglb.h, z80core/simz80-cb.c, z80core/simz80-dd.c, z80core/simz80-ddcb.c, z80core/simz80-ed.c, z80core/simz80-fd.c, z80core/simz80-fdcb.c, z80core/simz80.c, z80sim/srcsim/Makefile, z80sim/srcsim/sim.h.debug, z80sim/srcsim/sim.h.fast
Passes all tests (no, no undefined flags...)
=> first cut of alternative Z80 simulator optimized for code size

z80core/alt8080.h, z80core/altregs.h, z80core/altz80.h, z80core/simglb.c, z80core/simglb.h, z80core/simice.c
And some other tweaks to these simulators.
=> new register representation for alternative simulators

z80core/simz80.c
=> use in SLEEP_US in simz80.c

z80core/simcore.c, z80core/simcore.h
Don't really belong in simcore.h.
=> move port_in/port_out declaration to simcore.c

intelmdssim/conf/system.conf, intelmdssim/srcsim/Makefile, intelmdssim/srcsim/config.c, intelmdssim/srcsim/config.h, intelmdssim/srcsim/iosim.c, intelmdssim/srcsim/memsim.c, intelmdssim/srcsim/memsim.h, intelmdssim/srcsim/sim.h, intelmdssim/srcsim/simctl.c, iodevices/mds-isbc202.c, iodevices/mds-isbc202.h, iodevices/mds-monitor.c, iodevices/mds-monitor.h
Keep CPU in limbo after power on until reset is pressed.
Add mutex to interrupt code.
Adjust boot switch hack for running without the frontpanel.
Add baudrate simulation for more authentic feel.
Add Udo's copyright to mds-monitor.c since a lot of the code comes from other I/O devices.
Next up the disk controller.
Would be nice, if you code look over the intelmds code and tell me if I did something stupid or blatantly incorrect.
=> complete monitor module, other stuff

Makefile, iodevices/mds-isbc202.c
Comments are mostly from tarbell_fdc.c like a lot of the code.
=> sprinkle comments in iSBC 202 code, add intelmdssim to top level Makefile

picosim/CMakeLists.txt, picosim/disks.c, picosim/disks.h, picosim/picosim.c, picosim/picosim.h, picosim/simcfg.c, picosim/simio.c, picosim/simmem.c, picosim/simmem.h, picosim/stdio_msc_usb/CMakeLists.txt, picosim/stdio_msc_usb/include/msc_usb.h, picosim/stdio_msc_usb/include/stdio_msc_usb.h, picosim/stdio_msc_usb/include/tusb_config.h, picosim/stdio_msc_usb/msc_usb.c, picosim/stdio_msc_usb/reset_interface.c, picosim/stdio_msc_usb/stdio_msc_usb.c, picosim/stdio_msc_usb/stdio_msc_usb_descriptors.c
Please test, can't do this myself.
=> sync with RP2040-GEEK-80

z80core/simice.c
=> simice: use from,to arguments for dump and list

altairsim/srcsim/sim.h, altairsim/srcsim/simmem.h, cpmsim/srcsim/sim.h, cpmsim/srcsim/simmem.h, cromemcosim/srcsim/sim.h, cromemcosim/srcsim/simmem.h, doc/CREDITS, imsaisim/srcsim/sim.h, imsaisim/srcsim/simmem.h, intelmdssim/srcsim/sim.h, intelmdssim/srcsim/simmem.h, mosteksim/srcsim/sim.h, mosteksim/srcsim/simmem.h, picosim/srcsim/simmem.h, z80sim/srcsim/simmem.h
Add line to CREDITS, and copyright/history for previous commits.
=> add hardware breakpoint support to all simulators

picosim/srcsim/disks.c, picosim/srcsim/disks.h, picosim/srcsim/picosim.c, picosim/srcsim/simcfg.c, picosim/srcsim/simio.c, z80core/simice.c
Adds 'c', 'r', and '! ls' to the ICE.
save PC in simice.c:do_clock()
=> add missing commands to ICE, use bool where appropriate

altairsim/conf/panel.conf, cromemcosim/conf_2d/panel.conf, cromemcosim/conf_3d/panel.conf, frontpanel/lp_switch.h, imsaisim/conf_2d/panel.conf, imsaisim/conf_3d/panel.conf, intelmdssim/conf/panel.conf
The current fan sound sample will probably badly affect the calmness of the user after a short time...
=> default to no fan sound, small bit of formatting

z80core/simpanel.c
Still needs way to change address of display memory page.
Fixes compilation with X11.
=> add memory display to introspection panel
